apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: wsdl-hello-world
  description: Hello World example for WSDL
spec:
  type: wsdl
  lifecycle: deprecated
  owner: foo
  definition:
    $text: http://www.dneonline.com/calculator.asmx?wsdl
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wsdl-hello-world
spec:
  type: service
  lifecycle: production
  owner: user:development/guest
  providesApis:
    - wsdl-hello-world
